"""Create food_bank_items table

Revision ID: 3fd71fca1a71
Revises: 9cd691c63d1c
Create Date: 2025-04-14 22:13:25.923236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd71fca1a71'
down_revision = '9cd691c63d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_bank_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity_needed', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_bank_items')
    # ### end Alembic commands ###
