"""Create AdoptableAnimal model

Revision ID: 9cd691c63d1c
Revises: 0557e7c335bd
Create Date: 2025-04-14 12:54:59.648496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd691c63d1c'
down_revision = '0557e7c335bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoptable_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('amount_donated', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('behavior', sa.String(length=50), nullable=True),
    sa.Column('potty_trained', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoptable_animal')
    # ### end Alembic commands ###
