"""Create Volunteer table1

Revision ID: fa19bc626f62
Revises: 78d9a798d62c
Create Date: 2025-04-15 21:53:57.024607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa19bc626f62'
down_revision = '78d9a798d62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteers')
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('motivation', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('preferred_roles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.Text(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('availability')
        batch_op.drop_column('preferred_roles')
        batch_op.drop_column('motivation')
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    op.create_table('volunteers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('motivation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='volunteers_pkey'),
    sa.UniqueConstraint('email', name='volunteers_email_key')
    )
    # ### end Alembic commands ###
